# Define array function in Numpy, Tensorflow, Pytorch

In [1]:
import numpy as np
import tensorflow as tf
import torch

## Zeros

In [2]:
zeros_np = np.zeros((2,3))
zeros_np

array([[0., 0., 0.],
       [0., 0., 0.]])

In [3]:
zeros_pt = torch.zeros((3,3))
zeros_pt

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [4]:
zeros_tf = tf.zeros((3,4))
zeros_tf

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

## Ones

In [8]:
ones_np = np.ones((2,3))
ones_np

array([[1., 1., 1.],
       [1., 1., 1.]])

In [9]:
ones_pt = torch.ones((3,3))
ones_pt

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [10]:
ones_tf = tf.ones((3,4))
ones_tf

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>

## Full, fill

In [11]:
array_np = np.full((2,3), 5)
array_np

array([[5, 5, 5],
       [5, 5, 5]])

In [12]:
array_pt = torch.full((3,2), 2)
array_pt

tensor([[2, 2],
        [2, 2],
        [2, 2]])

In [14]:
array_tf = tf.fill((7,5), 8)
array_tf

<tf.Tensor: shape=(7, 5), dtype=int32, numpy=
array([[8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8]], dtype=int32)>

# Exercise

Ex 1: Write a program using the zeros function to create a Numpy array, Tensorflow tensor, Pytorch tensor that only contains the value zero with size (3, 4)?

In [15]:
np_arr = np.zeros((3,4))
pt_arr = torch.zeros((3,4))
tf_arr = tf.zeros((3,4))
np_arr, pt_arr, tf_arr

(array([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]),
 tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 <tf.Tensor: shape=(3, 4), dtype=float32, numpy=
 array([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]], dtype=float32)>)

Ex 2: Write a program using the ones function to create a Numpy array, Tensorflow tensor, Pytorch tensor containing only the value 1 with size (3, 4)?

In [16]:
np_arr_one = np.ones((3,4))
pt_arr_one = torch.ones((3,4))
tf_arr_one = tf.ones((3,4))
np_arr_one, pt_arr_one, tf_arr_one

(array([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]),
 tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 <tf.Tensor: shape=(3, 4), dtype=float32, numpy=
 array([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=float32)>)

Ex3: Write a program to create a Numpy array, Tensorflow tensor, Pytorch tensor containing only the value
number 5 with size (3, 4)?

In [17]:
np_arr_fullfill = np.full((3,4), 5)
pt_arr_fullfill = torch.full((3,4), 5)
tf_arr_fullfill = tf.fill((3,4), 5)
np_arr_fullfill, pt_arr_fullfill, tf_arr_fullfill

(array([[5, 5, 5, 5],
        [5, 5, 5, 5],
        [5, 5, 5, 5]]),
 tensor([[5, 5, 5, 5],
         [5, 5, 5, 5],
         [5, 5, 5, 5]]),
 <tf.Tensor: shape=(3, 4), dtype=int32, numpy=
 array([[5, 5, 5, 5],
        [5, 5, 5, 5],
        [5, 5, 5, 5]], dtype=int32)>)