# Array and Tensor in Pytorch/ Tensorflow

Array in Numpy and Tensor in Pytorch, Tensorflow are fundamental units for taking the computation in those library.  
* **Array** is a data structure that help stores and performs calculation on numaric data. Array can be a scalar, vector, matrix or tensor depend on the size of data.
* **Tensor in Pytorch and tensorflow** is a data structure like array in Numpy but it's designed for dealing with deep learning and parallel calculation, expectially calculate in CPU and TPU. It is a fundamental unit for storing and handling data

In [3]:
import numpy as np
import tensorflow as tf
import torch

listt = [4, 2, 5, 2, 4]

# Numpy
n = np.array(listt)
# Pytoch
m = torch.tensor(listt)
# Tensorflow
i = tf.constant(listt)
n, m, i

(array([4, 2, 5, 2, 4]),
 tensor([4, 2, 5, 2, 4]),
 <tf.Tensor: shape=(5,), dtype=int32, numpy=array([4, 2, 5, 2, 4], dtype=int32)>)

When we work with tensor, we can check their properties through some method such as:  
* **shape** size of tensor
* **dtype** the datatype of elemens in tensor
* **type** the type of object or tensor
* **device** (available in Pytorch and Tensorflow) help we know where the tensor is stored, CPU or GPU

# Exercise

## Ex 1: Write a program to create Numpy array, Tensorflow tensor, Pytorch tensor from 1-dimensional list?

In [4]:
list_1D = [x for x in range(20)]

In [22]:
array = np.array(list_1D)
print(array)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [21]:
tensor_1D_pt = torch.tensor(list_1D)
print(tensor_1D_pt)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19])


In [20]:
tensor_1D_tf = tf.convert_to_tensor(list_1D)
print(tensor_1D_tf)

tf.Tensor([ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19], shape=(20,), dtype=int32)


## Ex 2: Write a program to create Numpy array, Tensorflow tensor, Pytorch tensor from a 2-dimensional list. Then check the shape, dtype, type, device attributes from the newly created arrays and tensors?

In [16]:
list_2D = [[1,2,3], [4,5,6], [7,8,9]]

In [17]:
array = np.array(list_2D)
print(array)
print(array.shape)
print(array.dtype)
print(type(array))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
int64
<class 'numpy.ndarray'>


In [18]:
tensor_2D_pt = torch.tensor(list_2D)
print(tensor_2D_pt)
print(tensor_2D_pt.shape)
print(tensor_2D_pt.dtype)
print(type(tensor_2D_pt))
print(tensor_2D_pt.device)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
torch.Size([3, 3])
torch.int64
<class 'torch.Tensor'>
cpu


In [19]:
tensor_2D_tf = tf.convert_to_tensor(list_2D)
print(tensor_2D_tf)
print(tensor_2D_tf.shape)
print(tensor_2D_tf.dtype)
print(type(tensor_2D_tf))
print(tensor_2D_tf.device)

tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32)
(3, 3)
<dtype: 'int32'>
<class 'tensorflow.python.framework.ops.EagerTensor'>
/job:localhost/replica:0/task:0/device:CPU:0
